language: python
install:
  - 'pip install -r requirements.txt'
script:
  - 'make $TEST'
matrix:
  fast_finish: true
  include:
  - env: TEST='lint'
    python: '3.6'
  - env: TEST='test'
    python: '3.6'
